FROM node:22-alpine
WORKDIR /app

# Keep image tiny + tools for node-gyp if needed (bcryptjs is pure JS but ok)
RUN apk add --no-cache bash

COPY package*.json ./
RUN npm ci

COPY . .
EXPOSE 3001

CMD ["npm","run","dev"]
